---
title: "Exercise set 1"
author: "Zhipeng Zhu"
date: "1/20/2021"
output:
  html_document:
    theme: spacelab
    toc: no
    df_print: paged
  pdf_document: default
urlcolor: BrickRed
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Exercise 1

According to the plot `failureProbability.pdf`, most of the spikes are close to zero.
That is, most of them are not statistically significant. 
This means that the failure probability for each time is not highly correlated with the others. 
In our settings for the Bayesian model, we assume a beta prior on the `failureProbability`. 
The uncorrelated result from `failureProbability.pdf` match the prior on randomness.

# Exercise 2

$\gamma (x,z) = \text{prior} (p) \prod_{i=1}^{3} \text{likelihood} (x_i | p)$

$\text{likelihood} (x_i | p) = p^{x_i} (1-p)^{1-x_i}$

The joint distribution of $Z, X_1, \dots , X_3$ is $\gamma (x,z) = f_{X, Z} (x1, \dots, x3, p) = \prod_{i=1}^{3} p^{x_i} (1-p)^{1-x_i} \times 1 = p^{\sum x_i} (1-p)^{3- \sum x_i}$.

Let $s = x_1 + \dots + x_3$, the marginal distribution of $X_1, \dots , X_3$ can be calculated by integrating $\gamma (x,z)$ over $p$:

$f_X(x_1, \dots, x_3) = \int_{0}^{1} p^{s}(1-p)^{3-s}dp = B(s+1, 3-s+1)$ where $B(a,b) = \frac{\Gamma (a) \Gamma (b)}{\Gamma (a + b)}$. 


# Exercise 3

As we have derived the marginal distribution, then, the posterior distribution of $Z$ given $X_1 = x_1, \dots, X_3 = 0$ has the PDF as:

$f_{Z|X} (p|x_1, ..., x_3) = \frac{f_{X,Z}(x_1, \dots, x_3, p)}{f_X (x1, \dots, x_3)} = \frac{p^s (1-p)^{3-s}}{B(s+1, 3-s+1)}$

As the values of first three $X_i$ are given by zero, the PDF becomes:

$f_{Z|X} (p|x_1, ..., x_3) = \frac{p^s (1-p)^{3-s}}{B(s+1, 4-s)}$ where $s = 0$.

Therefore, $f_{Z|X} (p|x1, ..., x_3) = \frac{p^{0} (1-p)^{3- 0}}{B(0+1, 4-0)}$

For $X_4$, it has two possible outcomes which are $X_4 = 1$ and $X_4 = 0$. Based on the known value of first three $X_i$, we can calculate the posterior density of $X_4$ as

$\frac{p^{0} (1-p)^{4- 0}}{B(0+1, 4-0)}$ when $X_4 = 0$. By integrating over $p \in (0,1)$ we get $0.8$.

$\frac{p^{1} (1-p)^{4- 1}}{B(0+1, 4-0)}$ when $X_4 = 1$. By integrating over $p \in (0,1)$ we get $0.2$.

Both are corresponding to the posterior plot of `nextLaunch.pdf`, on which the density of $X_4 = 0$ is $0.8$ and the density of $X_4 = 1$ is $0.2$.

# Exercise 4

Based on the posterior computed in second step, we conclude that the probability of $X_4$ being a failure is 0.2, which is larger than $1/50$. Therefore, the Bayes estimator is $1$, which means we have to buy the insurance.

# Exercise 5
It may change. In this case, we only have three observed data which are $X_1, X_2, X_3$. As the size is small, changing the prior may have more effects on the decision. 